### generate Unique Ids
POST http://localhost:4004/catalog/generateUniqueId
Content-Type: application/json

{ 
     "vcRulesList": [ 
            {            

                      "product": "VCP_100",

                      "externalIdentification": "ex1",

                      "uniqueIDDescription": "Test",

                      "validFrom": "2023-08-01",

                      "validTo": "9999-12-31",

                      "characteristics": [               

                         { "characteristic": "CAMREAS", "characteristicValue": "C001234" },

                         { "characteristic": "CAMREAS", "characteristicValue": "C00123456" }

                ]

                }

  ]

}